name: Build and Publish the dicker image to Docker Hub!

on:
  push:
    branches: [ main ]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Build docker image
      run: docker build ./main.go --tag go-prog-image:$(date +%s)

    - name: Publish to docker hub!
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: srahul3/go-prog-image-actions
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}